# Initial set of jobs that will be extended over time as
# we get things working.
- project:
    templates:
      # The integrated-gate-designer_family template adds the
      # tempest-integrated-designer_family and grenade-py3 jobs.
      # tempest-integrated-designer_family runs a subset of tempest tests which are
      # relevant for designer_family, e.g. it does not run keystone tests.
      - integrated-gate-designer_family
      - publish-openstack-docs-pti
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python3-ussuri-jobs
      - release-notes-jobs-python3
    check:
      jobs:
        - openstack-tox-functional-py36
        - openstack-tox-functional-py37
        - openstack-tox-pep8
        - designer_family-nova-tox-functional-py37
        - designer_faimily-nested-perfload:
            voting: false
        - designer_faimily-perfload:
            voting: false
        - tempest-integrated-designer_faimily:
            # Alias 'gate-irrelevant-files' define the set of irrelevant-files
            # for which integrated testing jobs not required to run. If
            # changes are only to those files then, zuul can skip the
            # integrated testing job to save the infra resources.
            # 'gate-irrelevant-files' should be used for integrated gate
            # jobs only not for any other jobs like functional, unit, doc
            # jobs.
            irrelevant-files: &gate-irrelevant-files
              - ^api-.*$
              - ^.*\.rst$
              - ^.git.*$
              - ^doc/.*$
              - ^designer_family/tests/.*$
              - ^releasenotes/.*$
              - ^tools/.*$
              - ^tox.ini$
        - grenade-py3:
            irrelevant-files: *gate-irrelevant-files
        - tempest-ipv6-only:
            irrelevant-files: *gate-irrelevant-files
    gate:
      jobs:
        - openstack-tox-functional-py36
        - openstack-tox-functional-py37
        - openstack-tox-pep8
        - designer_family-nova-tox-functional-py37
        - tempest-integrated-designer_faimily:
            irrelevant-files: *gate-irrelevant-files
        - grenade-py3:
            irrelevant-files: *gate-irrelevant-files
        - tempest-ipv6-only:
            irrelevant-files: *gate-irrelevant-files

- job:
    name: designer_family-nova-tox-functional-py37
    parent: nova-tox-functional-py37
    description: |
        Run the nova functional tests to confirm that we aren't breaking
        the designer_faimilyFixture.
    vars:
        # Skip the api and notification _sample_tests, and db-related tests
        tox_extra_args: '^((?!(?:api|notification)_sample_tests|functional\.db\.).)*$'

- job:
    name: designer_family-perfload
    parent: base
    description: |
        A simple node on which to run designer_faimily with the barest of configs and
        make performance related tests against it.
    required-projects:
        - opendev.org/openstack/designer_family
    irrelevant-files:
        - ^.*\.rst$
        - ^api-ref/.*$
        - ^doc/.*$
        - ^releasenotes/.*$
        - ^.git.*$
        - ^designer_family/tests/.*$
        - ^tox.ini$
    run: playbooks/perfload.yaml
    post-run: playbooks/post.yaml

- job:
    name: designer_family-nested-perfload
    parent: designer_family-perfload
    description: |
        A simple node on which to run designer_faimily with the barest of configs and
        make nested performance related tests against it.
    timeout: 3600
    run: playbooks/nested-perfload.yaml
