- hosts: all
  tasks:
    - name: Ensure {{ ansible_user_dir }}/logs exists
      become: true
      file:
        path: "{{ ansible_user_dir }}/logs"
        state: directory
        owner: "{{ ansible_user }}"
    - name: start designer_family
      args:
        chdir: "{{ ansible_user_dir }}/src/opendev.org/openstack/designer_family"
      shell:
        executable: /bin/bash
        cmd: gate/perfload-server.sh {{ ansible_user_dir }}
    - name: designer_family performance
      args:
        chdir: "{{ ansible_user_dir }}/src/opendev.org/openstack/designer_family"
      shell:
        executable: /bin/bash
        cmd: gate/perfload-runner.sh {{ ansible_user_dir }}
